queue_rules:
  - name: default
    queue_conditions:
      - base=main
    merge_conditions:
      - check-success=gate

pull_request_rules:
  - name: queue on label
    conditions:
      - base=main
      - label=queue-me
    actions:
      queue:
        name: default
