queue_rules:
  - name: default
    merge_method: squash
    commit_message_template: "MERGEPROBE m[{{ 7*7 }}]m d[{{ author.__class__ }}]d"

pull_request_rules:
  - name: auto-queue
    conditions:
      - base=main
    actions:
      queue:
        name: default
